# Application Properties
spring:
  application:
    name: PandemicStats
  # Jpa Properties
  datasource:
    url: jdbc:postgresql://localhost:5432/pandemicstats
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

  # Liquibase properties
  liquibase:
    enabled: false

## Server Properties
server:
  port: 8000
